### ISSUE TITLE
Teleportation canceled (Private MP)

### ISSUE THREAD

**Issue by DrSpghetto** [Darkhax-Minecraft/Hunting-Dimension#26]
Just got to Age 1 with my friend and created the hunting dimension portal, i was able to enter it without any problems but he was getting an error in chat that says that a mod is blocking him from entering to the dimension (we both use the sevtech ages modpack)
this is what i get in the console when hes trying to enter it
`[11:41:45] [Server thread/ERROR] [Hunting Dimension]: * Teleportation was canceled!
[11:41:45] [Server thread/ERROR] [Hunting Dimension]: * This is not necessarily an issue.
[11:41:45] [Server thread/WARN] [Hunting Dimension]: *  at net.darkhax.huntingdim.event.EntityTravelToDimensionEventWrapped.setCanceled(EntityTravelToDimensionEventWrapped.java:28)
[11:41:45] [Server thread/WARN] [Hunting Dimension]: *  at net.darkhax.dimstages.DimensionStages.attemptEntryBlock(DimensionStages.java:75)
[11:41:45] [Server thread/WARN] [Hunting Dimension]: *  at net.darkhax.dimstages.DimensionStages.onDimChange(DimensionStages.java:44)
[11:41:45] [Server thread/WARN] [Hunting Dimension]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_969_DimensionStages_onDimChange_EntityTravelToDimensionEvent.invoke(.dynamic)
[11:41:45] [Server thread/WARN] [Hunting Dimension]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[11:41:45] [Server thread/WARN] [Hunting Dimension]: *  at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)...
[11:41:45] [Server thread/ERROR] [Hunting Dimension]: ********************************************************************************`

**Comment by DrSpghetto** [comment]
He had to sync the achivements with me, FIXED.

**Comment by Darkhax** [comment]
Glad to hear you worked it out.
